name: Run tests & flakehell lint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
#https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
# GitHub supported python versions
jobs:
  test:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        run: pip install poetry
      - name: Run all tests
        run: |
          poetry install
          poetry run python -m unittest -v tests/*.py
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run safety
        run: poetry run flakehell lint